sonar.projectKey=TheoVm_team-build-pokemon-1gq-tests
sonar.organization=theovm
sonar.sources=poketeams/app,poketeams/lib
sonar.tests=poketeams
sonar.test.inclusions=**/__tests__/**,**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.next/**,**/__mocks__/**,**/*.config.js,**/*.config.mjs,**/jest.setup.js
sonar.coverage.exclusions=poketeams/app/**,**/__tests__/**,**/__mocks__/**,**/*.config.js,**/*.config.mjs,**/jest.setup.js
sonar.javascript.lcov.reportPaths=poketeams/coverage/lcov.info
