name: CI - PokéTeams

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
          cache: 'npm'
          cache-dependency-path: poketeams/package-lock.json

      - name: Instalar dependências
        run: npm install
        working-directory: poketeams

      - name: Rodar lint
        run: npm run lint --if-present
        working-directory: poketeams

      - name: Rodar testes
        run: npm test
        working-directory: poketeams

      - name: Build do projeto
        run: npm run build
        working-directory: poketeams

      - name: Pipeline finalizado
        run: echo "CI executado com sucesso!"